# Use "null" to disable the parameter
# use "false" to turn on and "true" to turn on the function

- model_name: "En Arpa+"
  # the 4 blank characters here are important
  # do not remove
  graphemes: ["", "", "", "", "'", "-", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
  phonemes: ["", "", "", "", "aa", "ae", "ah", "ao", "aw", "ax", "ay", "b", "ch", "d", "dh", "dr", "dx", "eh", "er", "ey", "f", "g", "hh", "ih", "iy", "jh", "k", "l", "m", "n", "ng", "ow", "oy", "p", "q", "r", "s", "sh", "t", "th", "tr", "uh", "uw", "v", "w", "y", "z", "zh"]
  dict_path: "./g2p-en-arpa+/dict.txt"
  onnx_path: "./g2p-en-arpa+/g2p.onnx"
  split_character: false

- model_name: "JP Monophone"
  # the 4 blank characters here are important
  # do not remove
  graphemes: ["", "", "", "", "a", "b", "c", "d", "e", "f", "g",
            "h", "i", "j", "k", "m", "n", "o", "p", "r", "s",
            "t", "u", "v", "w", "y", "z", "あ", "い", "う", "え",
            "お", "ぁ", "ぃ", "ぅ", "ぇ", "ぉ", "か", "き", "く",
            "け", "こ", "さ", "し", "す", "せ", "そ", "ざ", "じ", "ず",
            "ぜ", "ぞ", "た", "ち", "つ", "て", "と", "だ", "ぢ", "づ", "で",
            "ど", "な", "に", "ぬ", "ね", "の", "は", "ひ", "ふ", "へ", "ほ",
            "ば", "び", "ぶ", "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ", "ま",
            "み", "む", "め", "も", "や", "ゆ", "よ", "ゃ", "ゅ", "ょ", "ら",
            "り", "る", "れ", "ろ", "わ", "を", "ん", "っ", "ヴ", "ゔ","゜",
            "ゐ", "ゑ", "ア", "イ", "ウ", "エ", "オ", "ァ", "ィ", "ゥ", "ェ",
            "ォ", "カ", "キ", "ク", "ケ", "コ", "サ", "シ", "ス", "セ", "ソ",
            "ザ", "ジ", "ズ", "ゼ", "ゾ", "タ", "チ", "ツ", "テ", "ト", "ダ",
            "ヂ", "ヅ", "デ", "ド", "ナ", "ニ", "ヌ", "ネ", "ノ", "ハ", "ヒ",
            "フ", "ヘ", "ホ", "バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ",
            "ペ", "ポ", "マ", "ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ャ",
            "ュ", "ョ", "ラ", "リ", "ル", "レ", "ロ", "ワ", "ヲ", "ン", "ッ",
            "ヰ", "ヱ", "息", "吸", "-", "R", "゜"]
  phonemes: ["", "", "", "", "A", "AP", "E", "I", "N", "O", "U",
            "SP", "a", "b", "by", "ch", "cl", "d", "dy", "e", "f", "g", "gw",
            "gy", "h", "hy", "i", "j", "k", "kw", "ky", "m", "my", "n",
            "ng", "ngy", "ny", "o", "p", "py", "r", "ry", "s", "sh", "t", "ts",
            "ty", "u", "v", "w", "y", "z"]
  dict_path: ["./g2p-jp-mono/katakana.txt",
              "./g2p-jp-mono/romaji.txt",
              "./g2p-jp-mono/special.txt",
              ./g2p-jp-mono/hiragana.txt]
  onnx_path: "null"
  split_character: true


- model_name: "DE X-S"
  # the 4 blank characters here are important
  # do not remove
  graphemes: ["", "", "", "", "'", "-", "a", "b", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "r", "s", "t", "u", "v", "w", "x", "y", "z", "ß", "ä", "ö", "ü", "c", "q", "é"]
  phonemes: ["", "", "", "", "a", "6", "e", "E", "i", "I", "u", "U", "o", "O", "y", "Y", "2", "9", "@", "aI", "aU", "OI", "w", "j", "p", "t", "k", "f", "s", "S", "C", "X", "h", "pf", "ts", "tS", "T", "m", "n", "N", "b", "d", "g", "v", "z", "l", "r", "dZ", "Z", "rh", "D", "rr", "R", "q", "E~", "O~", "a~"]
  dict_path: "null"
  onnx_path: "./g2p-de/g2p.onnx"
  split_character: false
